name: Backend CI/CD

on:
  push:
    branches:
      - dev
    paths:
      - "../apps/backend/**"
      - ".github/workflows/backend-cicd.yml"
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

environment:
  AWS_REGION: ${{ vars.AWS_REGION }}
  EKS_CLUSTER_NAME: ${{ vars.EKS_CLUSTER_NAME }}
  ECR_REPOSITORY: ${{ vars.ECR_BACKEND_REPOSITORY }}
  K8S_NAMESPACE: "portfolio"

jobs:
  deploy:
    name: Build and Deploy Backend
    runs-on: ubuntu-latest

    if: |
      (github.event_name == 'push' && github.ref_name == 'dev') ||
      (github.event_name == 'workflow_dispatch' && github.ref_name == 'main')

    environment: ${{ github.ref_name == 'main' && 'production' || 'dev' }}

    steps:
      - name: Checkout source
        uses: actions/checkout@v6

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v5
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Prepare image tags
        id: meta
        run: |
          SHORT_SHA="${GITHUB_SHA::7}"
          IMAGE_URI="${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}"
          echo "image_uri=${IMAGE_URI}" >> $GITHUB_OUTPUT
          echo "image_tag=${SHORT_SHA}" >> $GITHUB_OUTPUT
          echo "full_image=${IMAGE_URI}:${SHORT_SHA}" >> $GITHUB_OUTPUT

      - name: Build and push backend image
        uses: docker/build-push-action@v7
        with:
          context: ../apps/backend
          push: true
          tags: |
            ${{ steps.meta.outputs.full_image }}
            ${{ steps.meta.outputs.image_uri }}:${{ github.ref_name }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # - name: Update kubeconfig
      #   run: |
      #     aws eks update-config \
      #       --region "{AWS_REGION}" \
      #       --name "${EKS_CLUSTER_NAME}"

      # - name: Deploy backend to EKS
      #   run: |
      #     kubectl -n "${K8S_NAMESPACE}" rollout restart deployment
      #     kubectl -n "${K8S_NAMESPACE}" rollout status deployment
